services:
  - type: web
    name: kidanean-journal
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
